# This is your GitHub Actions workflow for deploying a Flask web app to Azure Web App

name: Build and deploy Python app to Azure Web App - testingpython12345

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests (optional)
        run: |
          # Add commands to run tests here

   - name: Zip artifact for deployment
  run: zip release.zip ./AzureWebAppForRCL/* -r

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'testingpython12345'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BA9AFCBFA4C4481E99C1F80F0E83D1B2 }}
